version: "3.8"
services:
  backend:
   build: ./
   ports:
     - "3000:3000"
   environment:
     - MONGO_URI=mongodb://db/blog
   depends_on:
     - db
  db:
   image: mongo:4.0-xenial
   ports:
     - 27017:27017
   volumes:
     - blog:/data/db
volumes:
  blog: 
